/*
 * Design: "Néon Fitness Flow" — Dark UI sportif avec accents néon
 * Phases: warmup (vert), workout (corail), cooldown (bleu)
 * Format: 45s effort / 15s transition
 */

export type Phase = "warmup" | "workout" | "cooldown";

export interface Exercise {
  id: number;
  phase: Phase;
  isTransition: boolean;
  name: string;
  duration: number; // seconds
  startTime: string; // "MM:SS"
  position: string;
  movement: string;
  coaching: string;
}

export const PHASE_LABELS: Record<Phase, string> = {
  warmup: "Echauffement",
  workout: "Pilates Strength",
  cooldown: "Retour au calme",
};

export const PHASE_COLORS: Record<Phase, string> = {
  warmup: "var(--color-warmup)",
  workout: "var(--color-workout)",
  cooldown: "var(--color-cooldown)",
};

export const exercises: Exercise[] = [
  // ===== WARMUP =====
  {
    id: 1,
    phase: "warmup",
    isTransition: false,
    name: "Mobilité Hanches 90/90",
    duration: 45,
    startTime: "00:00",
    position: "Assis au sol, jambes pliées à 90 degrés (une devant, une sur le côté).",
    movement: "Gardez les talons au sol et basculez doucement les deux genoux d'un côté, puis de l'autre, comme des essuie-glaces.",
    coaching: "On commence en douceur. Gardez le buste droit. Laissez vos hanches s'ouvrir naturellement. Respirez calmement.",
  },
  {
    id: 2,
    phase: "warmup",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "00:45",
    position: "",
    movement: "Préparez-vous pour le côté droit.",
    coaching: "Gardez la jambe droite devant.",
  },
  {
    id: 3,
    phase: "warmup",
    isTransition: false,
    name: "Rotation 90/90 (Droite)",
    duration: 45,
    startTime: "01:00",
    position: "Jambe droite devant en 90/90.",
    movement: "Croisez le bras gauche vers la droite, puis ouvrez grand le bras gauche vers l'arrière en tournant le buste pour ouvrir la poitrine.",
    coaching: "Inspirez en ouvrant la poitrine, expirez en croisant. Sentez l'étirement dans le dos et l'ouverture des épaules.",
  },
  {
    id: 4,
    phase: "warmup",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "01:45",
    position: "",
    movement: "Restez en position.",
    coaching: "On reste sur ce côté pour l'extension.",
  },
  {
    id: 5,
    phase: "warmup",
    isTransition: false,
    name: "Extension Hanches (Droite)",
    duration: 45,
    startTime: "02:00",
    position: "Toujours jambe droite devant.",
    movement: "Prenez appui sur vos genoux, levez les fesses du sol en poussant le bassin vers l'avant. Levez le bras gauche au-dessus de la tête. Redescendez doucement.",
    coaching: "Contractez les fessiers en haut. Poussez le bassin vers l'avant. On réveille le centre du corps !",
  },
  {
    id: 6,
    phase: "warmup",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "02:45",
    position: "",
    movement: "Changez de côté.",
    coaching: "Basculez les jambes, jambe gauche devant.",
  },
  {
    id: 7,
    phase: "warmup",
    isTransition: false,
    name: "Rotation 90/90 (Gauche)",
    duration: 45,
    startTime: "03:00",
    position: "Jambe gauche devant en 90/90.",
    movement: "Croisez le bras droit vers la gauche, puis ouvrez grand vers l'arrière.",
    coaching: "On équilibre de l'autre côté. Suivez votre main du regard pour accentuer la rotation de la colonne.",
  },
  {
    id: 8,
    phase: "warmup",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "03:45",
    position: "",
    movement: "Restez en position.",
    coaching: "Préparez-vous à monter le bassin.",
  },
  {
    id: 9,
    phase: "warmup",
    isTransition: false,
    name: "Extension Hanches (Gauche)",
    duration: 45,
    startTime: "04:00",
    position: "Jambe gauche devant.",
    movement: "Levez le bassin, contractez les fessiers, bras droit au ciel.",
    coaching: "Serrez fort les fessiers en haut. Grandissez-vous au maximum !",
  },
  {
    id: 10,
    phase: "warmup",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "04:45",
    position: "",
    movement: "Prenez les haltères.",
    coaching: "Attrapez vos haltères légers et allongez-vous sur le dos.",
  },

  // ===== WORKOUT =====
  {
    id: 11,
    phase: "workout",
    isTransition: false,
    name: "Deadbug avec Haltères",
    duration: 45,
    startTime: "05:00",
    position: "Allongé dos, jambes en tabletop (genoux 90° au-dessus des hanches), bras tendus plafond avec haltères.",
    movement: "Tendez la jambe droite vers le sol pendant que le bras gauche descend vers l'arrière. Revenez au centre. Changez de côté.",
    coaching: "Plaquez le bas du dos dans le tapis ! C'est le plus important. Expirez quand vous tendez la jambe, inspirez en revenant.",
  },
  {
    id: 12,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "05:45",
    position: "",
    movement: "Restez sur le dos.",
    coaching: "On garde les haltères à la poitrine.",
  },
  {
    id: 13,
    phase: "workout",
    isTransition: false,
    name: "Single Leg Stretch lesté",
    duration: 45,
    startTime: "06:00",
    position: "Allongé dos, épaules et tête légèrement décollées. Haltères à la poitrine.",
    movement: "Tendez une jambe à ras du sol pendant que vous ramenez l'autre genou vers la poitrine. Alternez avec contrôle.",
    coaching: "Le regard vers le nombril. Engagez les abdos profonds. Plus la jambe descend bas, plus c'est difficile.",
  },
  {
    id: 14,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "06:45",
    position: "",
    movement: "Posez les pieds.",
    coaching: "Pieds à plat près des fesses.",
  },
  {
    id: 15,
    phase: "workout",
    isTransition: false,
    name: "Pont Fessier avec Marche",
    duration: 45,
    startTime: "07:00",
    position: "Allongé dos, genoux pliés, pieds à plat. Haltères posés sur le bassin.",
    movement: "Montez le bassin en l'air. Maintenez la position. Décollez un pied pour ramener le genou vers la poitrine, reposez, puis l'autre.",
    coaching: "Gardez les hanches hautes et stables ! Imaginez un verre d'eau posé sur votre ventre, il ne doit pas se renverser.",
  },
  {
    id: 16,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "07:45",
    position: "",
    movement: "Passez face au sol.",
    coaching: "On se retourne en position de planche.",
  },
  {
    id: 17,
    phase: "workout",
    isTransition: false,
    name: "Planche vers Rotation",
    duration: 45,
    startTime: "08:00",
    position: "Planche sur les mains (haltères dans les mains si possible).",
    movement: "Pivotez sur le côté en planche latérale, levez un bras vers le plafond. Revenez face au sol, puis pivotez de l'autre côté.",
    coaching: "Contrôlez la descente. Engagez les obliques. Repoussez fort le sol avec la main d'appui.",
  },
  {
    id: 18,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "08:45",
    position: "",
    movement: "Descendez sur les coudes.",
    coaching: "On passe sur les avant-bras.",
  },
  {
    id: 19,
    phase: "workout",
    isTransition: false,
    name: "Planche coudes Taps Genoux",
    duration: 45,
    startTime: "09:00",
    position: "Planche sur les avant-bras.",
    movement: "Pliez doucement un genou pour effleurer le tapis, puis tendez la jambe. Alternez droite et gauche.",
    coaching: "Aspirer le nombril vers la colonne. Le dos reste parfaitement plat. C'est un mouvement minuscule mais puissant.",
  },
  {
    id: 20,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "09:45",
    position: "",
    movement: "Asseyez-vous.",
    coaching: "On s'assoit, prenez vos haltères.",
  },
  {
    id: 21,
    phase: "workout",
    isTransition: false,
    name: "Crunch Iso Torsion (V-Sit)",
    duration: 45,
    startTime: "10:00",
    position: "Assis, buste penché en arrière à 45° (V-sit), dos droit. Un haltère dans chaque main devant.",
    movement: "Ouvrez le bras droit sur le côté en tournant les épaules, revenez au centre. Puis le bras gauche.",
    coaching: "Si ça tire dans le dos, redressez-vous un peu. Sentez la taille qui travaille. Suivez l'haltère du regard.",
  },
  {
    id: 22,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "10:45",
    position: "",
    movement: "Allongez-vous.",
    coaching: "On s'allonge complètement sur le dos.",
  },
  {
    id: 23,
    phase: "workout",
    isTransition: false,
    name: "Roll Up avec Haltères",
    duration: 45,
    startTime: "11:00",
    position: "Allongé dos, jambes tendues vers le plafond. Haltères dans les mains.",
    movement: "Enroulez la colonne pour décoller les épaules et aller chercher les orteils avec les haltères. Redescendez doucement.",
    coaching: "Utilisez la force des abdominaux, pas l'élan ! Menton rentré. Expirez à la montée.",
  },
  {
    id: 24,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "11:45",
    position: "",
    movement: "Passez à 4 pattes.",
    coaching: "On passe à 4 pattes pour le travail des fessiers.",
  },
  {
    id: 25,
    phase: "workout",
    isTransition: false,
    name: "Abduction 4 pattes (Droite)",
    duration: 45,
    startTime: "12:00",
    position: "À 4 pattes. Poids coincé derrière le genou droit (ou leste cheville).",
    movement: "Levez la jambe droite pliée sur le côté (mouvement du chien) puis redescendez avec contrôle.",
    coaching: "Ne creusez pas le dos. Le mouvement part du fessier, pas des lombaires. Contrôlez le retour.",
  },
  {
    id: 26,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "12:45",
    position: "",
    movement: "Restez à 4 pattes.",
    coaching: "On garde la même jambe.",
  },
  {
    id: 27,
    phase: "workout",
    isTransition: false,
    name: "Arc-en-ciel (Droite)",
    duration: 45,
    startTime: "13:00",
    position: "À 4 pattes, jambe droite tendue vers l'arrière.",
    movement: "Dessinez un grand arc-en-ciel avec le bout du pied : touchez le sol à l'extérieur à droite, puis croisez pour toucher le sol à gauche.",
    coaching: "Dessinez un grand demi-cercle ! Serrez la fesse en haut du mouvement. Gardez les bras tendus.",
  },
  {
    id: 28,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "13:45",
    position: "",
    movement: "Passez sur le côté droit.",
    coaching: "Planche latérale sur le genou droit.",
  },
  {
    id: 29,
    phase: "workout",
    isTransition: false,
    name: "Planche Latérale Crunch (D)",
    duration: 45,
    startTime: "14:00",
    position: "Planche latérale appui genou droit/main droite. Haltère main gauche.",
    movement: "Tendez bras gauche au-dessus de la tête et jambe gauche. Ramenez coude gauche vers genou gauche (crunch), puis retendez.",
    coaching: "On travaille la taille et le moyen fessier. Expirez quand le coude touche le genou.",
  },
  {
    id: 30,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "14:45",
    position: "",
    movement: "Repassez à 4 pattes.",
    coaching: "On change de côté. À 4 pattes.",
  },
  {
    id: 31,
    phase: "workout",
    isTransition: false,
    name: "Abduction 4 pattes (Gauche)",
    duration: 45,
    startTime: "15:00",
    position: "À 4 pattes. Poids coincé derrière le genou gauche.",
    movement: "Levez la jambe gauche pliée sur le côté.",
    coaching: "On passe de l'autre côté ! Même concentration. Le centre est fort, le dos ne bouge pas.",
  },
  {
    id: 32,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "15:45",
    position: "",
    movement: "Restez à 4 pattes.",
    coaching: "On garde la jambe gauche.",
  },
  {
    id: 33,
    phase: "workout",
    isTransition: false,
    name: "Arc-en-ciel (Gauche)",
    duration: 45,
    startTime: "16:00",
    position: "À 4 pattes, jambe gauche tendue.",
    movement: "Arc-en-ciel avec la jambe gauche, de l'extérieur vers l'intérieur croisé.",
    coaching: "Hanches face au sol. Sentez la brûlure dans le fessier gauche. Allez chercher haut et loin !",
  },
  {
    id: 34,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "16:45",
    position: "",
    movement: "Passez sur le côté gauche.",
    coaching: "Planche latérale sur le genou gauche.",
  },
  {
    id: 35,
    phase: "workout",
    isTransition: false,
    name: "Planche Latérale Crunch (G)",
    duration: 45,
    startTime: "17:00",
    position: "Planche latérale appui genou gauche/main gauche. Haltère main droite.",
    movement: "Crunch coude droit vers genou droit.",
    coaching: "Dernier effort sur ce bloc ! Allongez bien la jambe et le bras à chaque répétition.",
  },
  {
    id: 36,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "17:45",
    position: "",
    movement: "Asseyez-vous.",
    coaching: "Asseyez-vous, mains derrière le dos.",
  },
  {
    id: 37,
    phase: "workout",
    isTransition: false,
    name: "Marche en Tabletop inversé",
    duration: 45,
    startTime: "18:00",
    position: "Assis, mains derrière le dos, montez le bassin pour former une table.",
    movement: "Maintenez le bassin haut et levez un genou vers la poitrine, reposez, puis l'autre.",
    coaching: "Ouvrez la poitrine. Poussez fort dans les talons. Si c'est trop dur, maintenez simplement la position haute.",
  },
  {
    id: 38,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "18:45",
    position: "",
    movement: "Passez sur le ventre.",
    coaching: "On s'allonge sur le ventre, sans les poids.",
  },
  {
    id: 39,
    phase: "workout",
    isTransition: false,
    name: "Extension Dos Ange de Neige",
    duration: 45,
    startTime: "19:00",
    position: "Allongé sur le ventre, bras tendus devant.",
    movement: "Décollez poitrine, bras et jambes. Amenez les bras vers l'arrière en écartant les jambes. Ramenez devant en resserrant.",
    coaching: "On renforce toute la chaîne postérieure. Regardez le tapis pour protéger la nuque. Mouvement fluide comme dans l'eau.",
  },
  {
    id: 40,
    phase: "workout",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "19:45",
    position: "",
    movement: "Posez tout le matériel.",
    coaching: "Bravo ! Posez les poids, on passe au retour au calme.",
  },

  // ===== COOLDOWN =====
  {
    id: 41,
    phase: "cooldown",
    isTransition: false,
    name: "Vagues de la Colonne",
    duration: 45,
    startTime: "20:00",
    position: "Posture de l'enfant (fesses sur les talons, genoux écartés).",
    movement: "Déroulez la colonne vers l'avant pour venir en position du Cobra (bassin vers le sol, poitrine ouverte). Repoussez pour revenir en posture de l'enfant.",
    coaching: "Respirez profondément. Déroulez le dos vertèbre par vertèbre. Relâchez la pression.",
  },
  {
    id: 42,
    phase: "cooldown",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "20:45",
    position: "",
    movement: "Restez à genoux.",
    coaching: "On reste sur les genoux.",
  },
  {
    id: 43,
    phase: "cooldown",
    isTransition: false,
    name: "Étirement du Chiot",
    duration: 45,
    startTime: "21:00",
    position: "À 4 pattes.",
    movement: "Gardez les hanches au-dessus des genoux, avancez les mains loin devant et laissez fondre la poitrine et le front vers le tapis.",
    coaching: "Sentez l'ouverture dans les épaules et le haut du dos. Laissez la gravité faire le travail.",
  },
  {
    id: 44,
    phase: "cooldown",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "21:45",
    position: "",
    movement: "Allongez-vous sur le dos.",
    coaching: "Passez sur le dos pour étirer les fessiers.",
  },
  {
    id: 45,
    phase: "cooldown",
    isTransition: false,
    name: "Étirement Fessier (Droite)",
    duration: 45,
    startTime: "22:00",
    position: "Allongé sur le dos.",
    movement: "Croisez la cheville droite sur le genou gauche (en forme de 4). Attrapez l'arrière de la cuisse gauche et tirez doucement vers vous.",
    coaching: "On étire le fessier droit qui a bien travaillé aujourd'hui. Gardez les épaules détendues sur le tapis.",
  },
  {
    id: 46,
    phase: "cooldown",
    isTransition: true,
    name: "Transition",
    duration: 15,
    startTime: "22:45",
    position: "",
    movement: "Changez de jambe.",
    coaching: "On inverse les jambes.",
  },
  {
    id: 47,
    phase: "cooldown",
    isTransition: false,
    name: "Étirement Fessier (Gauche)",
    duration: 45,
    startTime: "23:00",
    position: "Allongé sur le dos.",
    movement: "Croisez la cheville gauche sur le genou droit. Tirez vers vous.",
    coaching: "Fermez les yeux. Prenez une grande inspiration par le nez, et expirez par la bouche en relâchant tout le corps. Vous avez fait un super travail aujourd'hui.",
  },
];

export const TOTAL_DURATION = exercises.reduce((sum, ex) => sum + ex.duration, 0);

export function getExerciseNumber(exercise: Exercise): number {
  const mainExercises = exercises.filter((e) => !e.isTransition);
  const idx = mainExercises.findIndex((e) => e.id === exercise.id);
  return idx + 1;
}

export function getTotalMainExercises(): number {
  return exercises.filter((e) => !e.isTransition).length;
}
