/*
 * Design: "Néon Fitness Flow" — Dark UI sportif avec accents néon
 * Séance complète d'1 HEURE — Full Body Pilates Strength avec poids légers
 * Phases: warmup (vert ~8 min), workout (corail ~44 min), cooldown (bleu ~8 min)
 * Format: 45s effort / 15s transition
 */

import { resolveImageUrl } from "./imageUrls";

export type Phase = "warmup" | "workout" | "cooldown";

export interface Exercise {
  id: number;
  phase: Phase;
  isTransition: boolean;
  name: string;
  duration: number; // seconds
  startTime: string; // "MM:SS"
  position: string;
  movement: string;
  coaching: string;
  imageUrl: string; // URL de l'image illustrant l'exercice
  targetMuscles: string; // Muscles ciblés
}

export const PHASE_LABELS: Record<Phase, string> = {
  warmup: "Echauffement",
  workout: "Pilates Strength",
  cooldown: "Retour au calme",
};

export const PHASE_COLORS: Record<Phase, string> = {
  warmup: "var(--color-warmup)",
  workout: "var(--color-workout)",
  cooldown: "var(--color-cooldown)",
};

// Placeholder pour les transitions (pas d'image nécessaire)
const TRANS = "";

export const exercises: Exercise[] = [
  // ============================================================
  // PHASE 1 — ECHAUFFEMENT & MOBILITE (~8 min)
  // ============================================================
  {
    id: 1,
    phase: "warmup",
    isTransition: false,
    name: "Mobilité Hanches 90/90",
    duration: 45,
    startTime: "00:00",
    position: "Assis au sol, jambes pliées à 90 degrés (une devant, une sur le côté).",
    movement: "Gardez les talons au sol et basculez doucement les deux genoux d'un côté, puis de l'autre, comme des essuie-glaces.",
    coaching: "On commence en douceur. Gardez le buste droit. Laissez vos hanches s'ouvrir naturellement. Respirez calmement.",
    imageUrl: "IMG_WARMUP_1",
    targetMuscles: "Hanches, adducteurs",
  },
  {
    id: 2, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "00:45",
    position: "", movement: "Gardez la jambe droite devant.", coaching: "Préparez la rotation.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 3,
    phase: "warmup",
    isTransition: false,
    name: "Rotation 90/90 Droite",
    duration: 45,
    startTime: "01:00",
    position: "Jambe droite devant en 90/90.",
    movement: "Croisez le bras gauche vers la droite, puis ouvrez grand le bras gauche vers l'arrière en tournant le buste.",
    coaching: "Inspirez en ouvrant la poitrine, expirez en croisant. Sentez l'étirement dans le dos.",
    imageUrl: "IMG_WARMUP_2",
    targetMuscles: "Colonne vertébrale, obliques",
  },
  {
    id: 4, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "01:45",
    position: "", movement: "Restez en position.", coaching: "On reste sur ce côté pour l'extension.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 5,
    phase: "warmup",
    isTransition: false,
    name: "Extension Hanches Droite",
    duration: 45,
    startTime: "02:00",
    position: "Toujours jambe droite devant.",
    movement: "Prenez appui sur vos genoux, levez les fesses du sol en poussant le bassin vers l'avant. Levez le bras gauche au-dessus de la tête.",
    coaching: "Contractez les fessiers en haut. Poussez le bassin vers l'avant. On réveille le centre du corps !",
    imageUrl: "IMG_WARMUP_3",
    targetMuscles: "Fessiers, psoas",
  },
  {
    id: 6, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "02:45",
    position: "", movement: "Changez de côté.", coaching: "Basculez les jambes, jambe gauche devant.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 7,
    phase: "warmup",
    isTransition: false,
    name: "Rotation 90/90 Gauche",
    duration: 45,
    startTime: "03:00",
    position: "Jambe gauche devant en 90/90.",
    movement: "Croisez le bras droit vers la gauche, puis ouvrez grand vers l'arrière.",
    coaching: "On équilibre de l'autre côté. Suivez votre main du regard pour accentuer la rotation.",
    imageUrl: "IMG_WARMUP_2",
    targetMuscles: "Colonne vertébrale, obliques",
  },
  {
    id: 8, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "03:45",
    position: "", movement: "Restez en position.", coaching: "Préparez-vous à monter le bassin.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 9,
    phase: "warmup",
    isTransition: false,
    name: "Extension Hanches Gauche",
    duration: 45,
    startTime: "04:00",
    position: "Jambe gauche devant.",
    movement: "Levez le bassin, contractez les fessiers, bras droit au ciel.",
    coaching: "Serrez fort les fessiers en haut. Grandissez-vous au maximum !",
    imageUrl: "IMG_WARMUP_3",
    targetMuscles: "Fessiers, psoas",
  },
  {
    id: 10, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "04:45",
    position: "", movement: "Passez à 4 pattes.", coaching: "On passe en position de chat.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 11,
    phase: "warmup",
    isTransition: false,
    name: "Cat-Cow (Chat-Vache)",
    duration: 45,
    startTime: "05:00",
    position: "À 4 pattes, mains sous les épaules, genoux sous les hanches.",
    movement: "Inspirez en creusant le dos (vache), expirez en arrondissant le dos vers le plafond (chat). Alternez lentement.",
    coaching: "Mouvement fluide, vertèbre par vertèbre. Sentez chaque segment de votre colonne bouger.",
    imageUrl: "IMG_WARMUP_4",
    targetMuscles: "Colonne vertébrale, abdominaux",
  },
  {
    id: 12, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "05:45",
    position: "", movement: "Restez à 4 pattes.", coaching: "On va étirer le haut du corps.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 13,
    phase: "warmup",
    isTransition: false,
    name: "Thread the Needle (D)",
    duration: 45,
    startTime: "06:00",
    position: "À 4 pattes.",
    movement: "Passez le bras droit sous le corps vers la gauche en tournant le buste, épaule droite vers le sol. Revenez et ouvrez le bras vers le plafond.",
    coaching: "Sentez la rotation thoracique. Gardez les hanches stables et carrées.",
    imageUrl: "IMG_WARMUP_5",
    targetMuscles: "Thoracique, épaules",
  },
  {
    id: 14, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "06:45",
    position: "", movement: "Changez de bras.", coaching: "Même mouvement, bras gauche.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 15,
    phase: "warmup",
    isTransition: false,
    name: "Thread the Needle (G)",
    duration: 45,
    startTime: "07:00",
    position: "À 4 pattes.",
    movement: "Passez le bras gauche sous le corps vers la droite, épaule gauche vers le sol. Revenez et ouvrez vers le plafond.",
    coaching: "Expirez en passant le bras sous le corps. Inspirez en ouvrant. Mouvement lent et contrôlé.",
    imageUrl: "IMG_WARMUP_5",
    targetMuscles: "Thoracique, épaules",
  },
  {
    id: 16, phase: "warmup", isTransition: true, name: "Transition", duration: 15, startTime: "07:45",
    position: "", movement: "Prenez les haltères.", coaching: "Attrapez vos haltères légers et allongez-vous sur le dos. C'est parti pour le workout !", imageUrl: TRANS, targetMuscles: "",
  },

  // ============================================================
  // PHASE 2 — PILATES STRENGTH FULL BODY (~44 min)
  // ============================================================

  // --- BLOC 1 : ABDOMINAUX PROFONDS ---
  {
    id: 17,
    phase: "workout",
    isTransition: false,
    name: "Deadbug avec Haltères",
    duration: 45,
    startTime: "08:00",
    position: "Allongé dos, jambes en tabletop (genoux 90° au-dessus des hanches), bras tendus plafond avec haltères.",
    movement: "Tendez la jambe droite vers le sol pendant que le bras gauche descend vers l'arrière. Revenez au centre. Changez de côté.",
    coaching: "Plaquez le bas du dos dans le tapis ! C'est le plus important. Expirez quand vous tendez la jambe.",
    imageUrl: "IMG_DEADBUG",
    targetMuscles: "Transverse, grand droit",
  },
  {
    id: 18, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "08:45",
    position: "", movement: "Restez sur le dos.", coaching: "On garde les haltères à la poitrine.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 19,
    phase: "workout",
    isTransition: false,
    name: "Single Leg Stretch lesté",
    duration: 45,
    startTime: "09:00",
    position: "Allongé dos, épaules et tête légèrement décollées. Haltères à la poitrine.",
    movement: "Tendez une jambe à ras du sol pendant que vous ramenez l'autre genou vers la poitrine. Alternez avec contrôle.",
    coaching: "Le regard vers le nombril. Engagez les abdos profonds. Plus la jambe descend bas, plus c'est difficile.",
    imageUrl: "IMG_SINGLE_LEG",
    targetMuscles: "Abdominaux, psoas",
  },
  {
    id: 20, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "09:45",
    position: "", movement: "Restez sur le dos.", coaching: "Gardez les haltères, bras tendus.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 21,
    phase: "workout",
    isTransition: false,
    name: "Crunch Haltères au plafond",
    duration: 45,
    startTime: "10:00",
    position: "Allongé dos, jambes en tabletop, bras tendus vers le plafond avec haltères.",
    movement: "Décollez les épaules en poussant les haltères vers le plafond. Redescendez lentement.",
    coaching: "Ne tirez pas sur la nuque ! Poussez les haltères droit vers le ciel. Expirez à la montée.",
    imageUrl: "IMG_CRUNCH",
    targetMuscles: "Grand droit, transverse",
  },
  {
    id: 22, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "10:45",
    position: "", movement: "Restez sur le dos.", coaching: "On passe aux obliques.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 23,
    phase: "workout",
    isTransition: false,
    name: "Bicycle Crunch lesté",
    duration: 45,
    startTime: "11:00",
    position: "Allongé dos, un haltère tenu à deux mains devant la poitrine.",
    movement: "Décollez les épaules, amenez le coude droit vers le genou gauche, puis alternez. Mouvement lent et contrôlé.",
    coaching: "Tournez les épaules, pas juste les coudes ! Sentez les obliques travailler. Lent et précis.",
    imageUrl: "IMG_BICYCLE",
    targetMuscles: "Obliques, grand droit",
  },
  {
    id: 24, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "11:45",
    position: "", movement: "Posez les pieds à plat.", coaching: "Pieds à plat près des fesses, haltères sur le bassin.", imageUrl: TRANS, targetMuscles: "",
  },

  // --- BLOC 2 : FESSIERS & CUISSES ---
  {
    id: 25,
    phase: "workout",
    isTransition: false,
    name: "Pont Fessier lesté",
    duration: 45,
    startTime: "12:00",
    position: "Allongé dos, genoux pliés, pieds à plat. Haltères posés sur le bassin.",
    movement: "Montez le bassin en serrant les fessiers. Maintenez 2 secondes en haut. Redescendez lentement.",
    coaching: "Serrez fort les fessiers en haut ! Imaginez que vous tenez une pièce entre vos fesses. Ne creusez pas le dos.",
    imageUrl: "IMG_BRIDGE",
    targetMuscles: "Grand fessier, ischio-jambiers",
  },
  {
    id: 26, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "12:45",
    position: "", movement: "Restez en position.", coaching: "On ajoute la marche.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 27,
    phase: "workout",
    isTransition: false,
    name: "Pont Fessier avec Marche",
    duration: 45,
    startTime: "13:00",
    position: "Allongé dos, bassin en l'air, haltères sur le bassin.",
    movement: "Maintenez le bassin haut. Décollez un pied pour ramener le genou vers la poitrine, reposez, puis l'autre.",
    coaching: "Gardez les hanches hautes et stables ! Imaginez un verre d'eau posé sur votre ventre.",
    imageUrl: "IMG_BRIDGE_MARCH",
    targetMuscles: "Fessiers, stabilisateurs",
  },
  {
    id: 28, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "13:45",
    position: "", movement: "Restez sur le dos.", coaching: "On passe au pont une jambe.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 29,
    phase: "workout",
    isTransition: false,
    name: "Pont Fessier 1 jambe (D)",
    duration: 45,
    startTime: "14:00",
    position: "Allongé dos, jambe droite tendue vers le plafond, pied gauche au sol.",
    movement: "Montez le bassin en poussant dans le talon gauche. Gardez la jambe droite tendue vers le ciel.",
    coaching: "C'est intense ! Serrez le fessier gauche. Si c'est trop dur, pliez la jambe en l'air.",
    imageUrl: "IMG_SINGLE_BRIDGE",
    targetMuscles: "Grand fessier, ischio-jambiers",
  },
  {
    id: 30, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "14:45",
    position: "", movement: "Changez de jambe.", coaching: "Jambe gauche en l'air maintenant.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 31,
    phase: "workout",
    isTransition: false,
    name: "Pont Fessier 1 jambe (G)",
    duration: 45,
    startTime: "15:00",
    position: "Allongé dos, jambe gauche tendue vers le plafond, pied droit au sol.",
    movement: "Montez le bassin en poussant dans le talon droit.",
    coaching: "On équilibre ! Même intensité de chaque côté. Serrez le fessier droit.",
    imageUrl: "IMG_SINGLE_BRIDGE",
    targetMuscles: "Grand fessier, ischio-jambiers",
  },
  {
    id: 32, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "15:45",
    position: "", movement: "Mettez-vous debout.", coaching: "On se lève doucement pour les squats.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 33,
    phase: "workout",
    isTransition: false,
    name: "Goblet Squat",
    duration: 45,
    startTime: "16:00",
    position: "Debout, pieds largeur épaules, un haltère tenu à deux mains devant la poitrine.",
    movement: "Descendez en squat profond, coudes entre les genoux. Poussez dans les talons pour remonter.",
    coaching: "Poitrine haute, genoux vers l'extérieur. Descendez comme si vous vous asseyiez sur une chaise invisible.",
    imageUrl: "IMG_GOBLET_SQUAT",
    targetMuscles: "Quadriceps, fessiers",
  },
  {
    id: 34, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "16:45",
    position: "", movement: "Restez debout.", coaching: "On passe aux fentes.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 35,
    phase: "workout",
    isTransition: false,
    name: "Fente arrière alternée",
    duration: 45,
    startTime: "17:00",
    position: "Debout, un haltère dans chaque main le long du corps.",
    movement: "Faites un grand pas en arrière, genou arrière vers le sol. Poussez pour revenir. Alternez.",
    coaching: "Gardez le buste droit. Le genou avant ne dépasse pas les orteils. Mouvement contrôlé.",
    imageUrl: "IMG_REVERSE_LUNGE",
    targetMuscles: "Quadriceps, fessiers, ischio-jambiers",
  },
  {
    id: 36, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "17:45",
    position: "", movement: "Restez debout.", coaching: "On reste sur les jambes.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 37,
    phase: "workout",
    isTransition: false,
    name: "Sumo Squat avec Haltère",
    duration: 45,
    startTime: "18:00",
    position: "Debout, pieds très écartés, pointes vers l'extérieur. Un haltère tenu à deux mains entre les jambes.",
    movement: "Descendez en squat sumo, genoux vers l'extérieur. Remontez en serrant les adducteurs.",
    coaching: "Dos droit, poitrine ouverte. Sentez l'intérieur des cuisses travailler à la remontée.",
    imageUrl: "IMG_SUMO_SQUAT",
    targetMuscles: "Adducteurs, fessiers, quadriceps",
  },
  {
    id: 38, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "18:45",
    position: "", movement: "Restez debout.", coaching: "On passe au soulevé de terre.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 39,
    phase: "workout",
    isTransition: false,
    name: "Romanian Deadlift",
    duration: 45,
    startTime: "19:00",
    position: "Debout, pieds largeur hanches, un haltère dans chaque main devant les cuisses.",
    movement: "Penchez le buste vers l'avant en poussant les fesses vers l'arrière, haltères glissent le long des jambes. Remontez en serrant les fessiers.",
    coaching: "Dos PLAT ! Regardez 2 mètres devant vous. Sentez l'étirement derrière les cuisses. Serrez les fessiers en haut.",
    imageUrl: "IMG_RDL",
    targetMuscles: "Ischio-jambiers, fessiers, lombaires",
  },
  {
    id: 40, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "19:45",
    position: "", movement: "Restez debout.", coaching: "On passe au RDL une jambe.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 41,
    phase: "workout",
    isTransition: false,
    name: "RDL 1 jambe (Droite)",
    duration: 45,
    startTime: "20:00",
    position: "Debout sur la jambe gauche, haltère dans la main droite.",
    movement: "Penchez le buste vers l'avant en levant la jambe droite vers l'arrière. Formez un T avec le corps. Revenez debout.",
    coaching: "Équilibre et contrôle ! Fixez un point devant vous. Gardez la hanche droite vers le sol.",
    imageUrl: "IMG_SINGLE_RDL",
    targetMuscles: "Ischio-jambiers, fessiers, équilibre",
  },
  {
    id: 42, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "20:45",
    position: "", movement: "Changez de jambe.", coaching: "Même exercice, autre côté.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 43,
    phase: "workout",
    isTransition: false,
    name: "RDL 1 jambe (Gauche)",
    duration: 45,
    startTime: "21:00",
    position: "Debout sur la jambe droite, haltère dans la main gauche.",
    movement: "Penchez le buste vers l'avant en levant la jambe gauche vers l'arrière.",
    coaching: "Même concentration ! Gardez le dos plat et la hanche face au sol.",
    imageUrl: "IMG_SINGLE_RDL",
    targetMuscles: "Ischio-jambiers, fessiers, équilibre",
  },
  {
    id: 44, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "21:45",
    position: "", movement: "Allongez-vous face au sol.", coaching: "On passe au haut du corps. Face au sol.", imageUrl: TRANS, targetMuscles: "",
  },

  // --- BLOC 3 : HAUT DU CORPS ---
  {
    id: 45,
    phase: "workout",
    isTransition: false,
    name: "Push-Up (Pompes genoux)",
    duration: 45,
    startTime: "22:00",
    position: "Face au sol, mains largeur épaules, genoux au sol (ou pieds pour les plus avancés).",
    movement: "Descendez la poitrine vers le sol en pliant les coudes. Poussez pour remonter.",
    coaching: "Corps gainé de la tête aux genoux ! Coudes à 45 degrés, pas sur les côtés. Expirez en poussant.",
    imageUrl: "IMG_PUSHUP",
    targetMuscles: "Pectoraux, triceps, épaules",
  },
  {
    id: 46, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "22:45",
    position: "", movement: "Restez face au sol.", coaching: "On reste au sol pour le rowing.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 47,
    phase: "workout",
    isTransition: false,
    name: "Prone Row (Rowing allongé)",
    duration: 45,
    startTime: "23:00",
    position: "Allongé sur le ventre, un haltère dans chaque main, bras tendus devant.",
    movement: "Décollez la poitrine et tirez les coudes vers l'arrière en serrant les omoplates. Tendez les bras devant et reposez.",
    coaching: "Serrez les omoplates comme si vous teniez un crayon entre elles ! Décollez la poitrine du sol.",
    imageUrl: "IMG_PRONE_ROW",
    targetMuscles: "Dorsaux, rhomboïdes, trapèzes",
  },
  {
    id: 48, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "23:45",
    position: "", movement: "Restez sur le ventre.", coaching: "On enchaîne avec le superman.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 49,
    phase: "workout",
    isTransition: false,
    name: "Superman avec Haltères",
    duration: 45,
    startTime: "24:00",
    position: "Allongé sur le ventre, bras tendus devant avec haltères.",
    movement: "Décollez simultanément bras, poitrine et jambes du sol. Maintenez 2 secondes. Reposez.",
    coaching: "Regardez le tapis pour protéger la nuque. Serrez les fessiers. Mouvement lent et contrôlé.",
    imageUrl: "IMG_SUPERMAN",
    targetMuscles: "Chaîne postérieure, lombaires",
  },
  {
    id: 50, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "24:45",
    position: "", movement: "Restez sur le ventre.", coaching: "On passe à l'ange de neige.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 51,
    phase: "workout",
    isTransition: false,
    name: "Ange de Neige",
    duration: 45,
    startTime: "25:00",
    position: "Allongé sur le ventre, bras tendus devant.",
    movement: "Décollez poitrine, bras et jambes. Amenez les bras vers l'arrière en écartant les jambes. Ramenez devant en resserrant.",
    coaching: "Mouvement fluide comme dans l'eau. Serrez les omoplates quand les bras sont en arrière.",
    imageUrl: "IMG_SNOW_ANGEL",
    targetMuscles: "Dos, épaules, fessiers",
  },
  {
    id: 52, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "25:45",
    position: "", movement: "Retournez-vous sur le dos.", coaching: "On passe au chest press.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 53,
    phase: "workout",
    isTransition: false,
    name: "Floor Chest Press",
    duration: 45,
    startTime: "26:00",
    position: "Allongé dos, genoux pliés, un haltère dans chaque main, coudes au sol à 90°.",
    movement: "Poussez les haltères vers le plafond en tendant les bras. Redescendez lentement coudes au sol.",
    coaching: "Expirez en poussant. Contrôlez la descente, ne laissez pas tomber les coudes. Serrez les pectoraux en haut.",
    imageUrl: "IMG_CHEST_PRESS",
    targetMuscles: "Pectoraux, triceps",
  },
  {
    id: 54, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "26:45",
    position: "", movement: "Restez sur le dos.", coaching: "On passe au pullover.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 55,
    phase: "workout",
    isTransition: false,
    name: "Pullover allongé",
    duration: 45,
    startTime: "27:00",
    position: "Allongé dos, genoux pliés. Un haltère tenu à deux mains au-dessus de la poitrine.",
    movement: "Descendez l'haltère vers l'arrière de la tête en gardant les bras légèrement fléchis. Ramenez au-dessus de la poitrine.",
    coaching: "Sentez l'étirement dans les dorsaux et les pectoraux. Gardez les côtes basses, ne creusez pas le dos.",
    imageUrl: "IMG_PULLOVER",
    targetMuscles: "Dorsaux, pectoraux, triceps",
  },
  {
    id: 56, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "27:45",
    position: "", movement: "Mettez-vous debout.", coaching: "Debout pour les épaules.", imageUrl: TRANS, targetMuscles: "",
  },

  // --- BLOC 4 : EPAULES & BRAS ---
  {
    id: 57,
    phase: "workout",
    isTransition: false,
    name: "Shoulder Press",
    duration: 45,
    startTime: "28:00",
    position: "Debout, pieds largeur hanches, un haltère dans chaque main à hauteur des épaules.",
    movement: "Poussez les haltères au-dessus de la tête. Redescendez lentement à hauteur des oreilles.",
    coaching: "Engagez les abdos pour protéger le dos. Ne creusez pas les lombaires. Poussez droit vers le ciel.",
    imageUrl: "IMG_SHOULDER_PRESS",
    targetMuscles: "Deltoïdes, triceps",
  },
  {
    id: 58, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "28:45",
    position: "", movement: "Restez debout.", coaching: "On passe aux élévations latérales.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 59,
    phase: "workout",
    isTransition: false,
    name: "Élévations latérales",
    duration: 45,
    startTime: "29:00",
    position: "Debout, un haltère dans chaque main le long du corps.",
    movement: "Levez les bras sur les côtés jusqu'à hauteur des épaules. Redescendez lentement.",
    coaching: "Coudes légèrement fléchis. Montez les coudes, pas les mains. Contrôlez la descente.",
    imageUrl: "IMG_LATERAL_RAISE",
    targetMuscles: "Deltoïdes latéraux",
  },
  {
    id: 60, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "29:45",
    position: "", movement: "Restez debout.", coaching: "On passe aux élévations frontales.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 61,
    phase: "workout",
    isTransition: false,
    name: "Élévations frontales alternées",
    duration: 45,
    startTime: "30:00",
    position: "Debout, un haltère dans chaque main devant les cuisses.",
    movement: "Levez un bras devant vous jusqu'à hauteur des épaules. Redescendez et alternez.",
    coaching: "Bras tendu mais pas verrouillé. Gardez le corps stable, pas de balancement.",
    imageUrl: "IMG_FRONT_RAISE",
    targetMuscles: "Deltoïdes antérieurs",
  },
  {
    id: 62, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "30:45",
    position: "", movement: "Penchez le buste.", coaching: "On passe au rowing penché.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 63,
    phase: "workout",
    isTransition: false,
    name: "Bent-Over Row",
    duration: 45,
    startTime: "31:00",
    position: "Debout, buste penché à 45°, un haltère dans chaque main, bras pendants.",
    movement: "Tirez les coudes vers l'arrière en serrant les omoplates. Redescendez lentement.",
    coaching: "Dos plat ! Regardez le sol 1 mètre devant vous. Serrez les omoplates en haut du mouvement.",
    imageUrl: "IMG_BENT_ROW",
    targetMuscles: "Dorsaux, rhomboïdes, biceps",
  },
  {
    id: 64, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "31:45",
    position: "", movement: "Restez penché.", coaching: "On enchaîne avec le reverse fly.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 65,
    phase: "workout",
    isTransition: false,
    name: "Reverse Fly (Oiseau)",
    duration: 45,
    startTime: "32:00",
    position: "Debout, buste penché à 45°, un haltère dans chaque main.",
    movement: "Ouvrez les bras sur les côtés en serrant les omoplates. Redescendez lentement.",
    coaching: "Imaginez que vous ouvrez des ailes ! Coudes légèrement fléchis. Sentez le haut du dos travailler.",
    imageUrl: "IMG_REVERSE_FLY",
    targetMuscles: "Deltoïdes postérieurs, rhomboïdes",
  },
  {
    id: 66, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "32:45",
    position: "", movement: "Redressez-vous.", coaching: "On passe aux biceps.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 67,
    phase: "workout",
    isTransition: false,
    name: "Biceps Curl",
    duration: 45,
    startTime: "33:00",
    position: "Debout, un haltère dans chaque main, paumes vers l'avant.",
    movement: "Fléchissez les coudes pour monter les haltères vers les épaules. Redescendez lentement.",
    coaching: "Coudes collés au corps ! Ne balancez pas. Contrôlez la descente sur 3 secondes.",
    imageUrl: "IMG_BICEPS_CURL",
    targetMuscles: "Biceps",
  },
  {
    id: 68, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "33:45",
    position: "", movement: "Restez debout.", coaching: "On passe aux triceps.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 69,
    phase: "workout",
    isTransition: false,
    name: "Triceps Kickback",
    duration: 45,
    startTime: "34:00",
    position: "Debout, buste penché, coudes fléchis à 90° le long du corps.",
    movement: "Tendez les bras vers l'arrière en gardant les coudes fixes. Revenez à 90°.",
    coaching: "Seuls les avant-bras bougent ! Serrez les triceps en haut. Mouvement lent et précis.",
    imageUrl: "IMG_TRICEPS_KICK",
    targetMuscles: "Triceps",
  },
  {
    id: 70, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "34:45",
    position: "", movement: "Passez en position de planche.", coaching: "On passe au gainage et au core.", imageUrl: TRANS, targetMuscles: "",
  },

  // --- BLOC 5 : CORE & PLANCHES ---
  {
    id: 71,
    phase: "workout",
    isTransition: false,
    name: "Planche vers Rotation",
    duration: 45,
    startTime: "35:00",
    position: "Planche sur les mains (haltères dans les mains si possible).",
    movement: "Pivotez sur le côté en planche latérale, levez un bras vers le plafond. Revenez face au sol, puis pivotez de l'autre côté.",
    coaching: "Contrôlez la rotation. Engagez les obliques. Repoussez fort le sol avec la main d'appui.",
    imageUrl: "IMG_PLANK_ROTATION",
    targetMuscles: "Obliques, épaules, core",
  },
  {
    id: 72, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "35:45",
    position: "", movement: "Descendez sur les coudes.", coaching: "On passe sur les avant-bras.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 73,
    phase: "workout",
    isTransition: false,
    name: "Planche coudes Taps Genoux",
    duration: 45,
    startTime: "36:00",
    position: "Planche sur les avant-bras.",
    movement: "Pliez doucement un genou pour effleurer le tapis, puis tendez la jambe. Alternez droite et gauche.",
    coaching: "Aspirez le nombril vers la colonne. Le dos reste parfaitement plat. Mouvement minuscule mais puissant.",
    imageUrl: "IMG_PLANK_KNEE",
    targetMuscles: "Transverse, core profond",
  },
  {
    id: 74, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "36:45",
    position: "", movement: "Restez en planche coudes.", coaching: "On ajoute les hip dips.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 75,
    phase: "workout",
    isTransition: false,
    name: "Hip Dips (Planche coudes)",
    duration: 45,
    startTime: "37:00",
    position: "Planche sur les avant-bras.",
    movement: "Basculez les hanches vers la droite pour effleurer le sol, revenez au centre, puis vers la gauche.",
    coaching: "Contrôlez le mouvement ! Ne vous effondrez pas. Sentez les obliques brûler.",
    imageUrl: "IMG_HIP_DIPS",
    targetMuscles: "Obliques, core",
  },
  {
    id: 76, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "37:45",
    position: "", movement: "Asseyez-vous.", coaching: "On s'assoit pour le V-sit.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 77,
    phase: "workout",
    isTransition: false,
    name: "V-Sit Torsion avec Haltère",
    duration: 45,
    startTime: "38:00",
    position: "Assis, buste penché en arrière à 45° (V-sit), dos droit. Un haltère tenu à deux mains.",
    movement: "Tournez le buste à droite en amenant l'haltère vers le sol, puis à gauche.",
    coaching: "Si ça tire dans le dos, redressez-vous un peu. Sentez la taille qui travaille. Pieds décollés du sol pour plus de défi.",
    imageUrl: "IMG_VSIT",
    targetMuscles: "Obliques, grand droit",
  },
  {
    id: 78, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "38:45",
    position: "", movement: "Allongez-vous sur le dos.", coaching: "On s'allonge pour le roll up.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 79,
    phase: "workout",
    isTransition: false,
    name: "Roll Up avec Haltères",
    duration: 45,
    startTime: "39:00",
    position: "Allongé dos, jambes tendues, haltères dans les mains au-dessus de la tête.",
    movement: "Enroulez la colonne pour monter assis, haltères vers les pieds. Redescendez lentement vertèbre par vertèbre.",
    coaching: "Utilisez la force des abdominaux, pas l'élan ! Menton rentré. Expirez à la montée.",
    imageUrl: "IMG_ROLLUP",
    targetMuscles: "Grand droit, psoas",
  },
  {
    id: 80, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "39:45",
    position: "", movement: "Restez sur le dos.", coaching: "On passe au hundred.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 81,
    phase: "workout",
    isTransition: false,
    name: "Hundred Pilates",
    duration: 45,
    startTime: "40:00",
    position: "Allongé dos, épaules décollées, jambes en tabletop ou tendues à 45°.",
    movement: "Bras le long du corps, pompez les bras de haut en bas rapidement. Inspirez 5 battements, expirez 5 battements.",
    coaching: "C'est LE classique du Pilates ! Gardez le bas du dos plaqué. Pompez avec énergie !",
    imageUrl: "IMG_HUNDRED",
    targetMuscles: "Abdominaux, stabilisateurs",
  },
  {
    id: 82, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "40:45",
    position: "", movement: "Passez à 4 pattes.", coaching: "On passe aux fessiers à 4 pattes.", imageUrl: TRANS, targetMuscles: "",
  },

  // --- BLOC 6 : FESSIERS ISOLÉS ---
  {
    id: 83,
    phase: "workout",
    isTransition: false,
    name: "Abduction 4 pattes (D)",
    duration: 45,
    startTime: "41:00",
    position: "À 4 pattes. Poids coincé derrière le genou droit.",
    movement: "Levez la jambe droite pliée sur le côté (mouvement du chien) puis redescendez avec contrôle.",
    coaching: "Ne creusez pas le dos. Le mouvement part du fessier, pas des lombaires.",
    imageUrl: "IMG_ABDUCTION",
    targetMuscles: "Moyen fessier",
  },
  {
    id: 84, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "41:45",
    position: "", movement: "Restez à 4 pattes.", coaching: "On garde la même jambe.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 85,
    phase: "workout",
    isTransition: false,
    name: "Arc-en-ciel (Droite)",
    duration: 45,
    startTime: "42:00",
    position: "À 4 pattes, jambe droite tendue vers l'arrière.",
    movement: "Dessinez un grand arc-en-ciel avec le bout du pied : touchez le sol à droite, puis croisez pour toucher à gauche.",
    coaching: "Grand demi-cercle ! Serrez la fesse en haut du mouvement. Gardez les bras tendus.",
    imageUrl: "IMG_RAINBOW",
    targetMuscles: "Grand fessier, moyen fessier",
  },
  {
    id: 86, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "42:45",
    position: "", movement: "Passez sur le côté droit.", coaching: "Planche latérale sur le genou droit.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 87,
    phase: "workout",
    isTransition: false,
    name: "Planche Latérale Crunch (D)",
    duration: 45,
    startTime: "43:00",
    position: "Planche latérale appui genou droit/main droite. Haltère main gauche.",
    movement: "Tendez bras gauche au-dessus de la tête et jambe gauche. Ramenez coude vers genou (crunch).",
    coaching: "On travaille la taille et le moyen fessier. Expirez quand le coude touche le genou.",
    imageUrl: "IMG_SIDE_PLANK_CRUNCH",
    targetMuscles: "Obliques, moyen fessier",
  },
  {
    id: 88, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "43:45",
    position: "", movement: "Repassez à 4 pattes.", coaching: "On change de côté.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 89,
    phase: "workout",
    isTransition: false,
    name: "Abduction 4 pattes (G)",
    duration: 45,
    startTime: "44:00",
    position: "À 4 pattes. Poids coincé derrière le genou gauche.",
    movement: "Levez la jambe gauche pliée sur le côté.",
    coaching: "Même concentration ! Le centre est fort, le dos ne bouge pas.",
    imageUrl: "IMG_ABDUCTION",
    targetMuscles: "Moyen fessier",
  },
  {
    id: 90, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "44:45",
    position: "", movement: "Restez à 4 pattes.", coaching: "On garde la jambe gauche.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 91,
    phase: "workout",
    isTransition: false,
    name: "Arc-en-ciel (Gauche)",
    duration: 45,
    startTime: "45:00",
    position: "À 4 pattes, jambe gauche tendue.",
    movement: "Arc-en-ciel avec la jambe gauche.",
    coaching: "Hanches face au sol. Sentez la brûlure dans le fessier gauche !",
    imageUrl: "IMG_RAINBOW",
    targetMuscles: "Grand fessier, moyen fessier",
  },
  {
    id: 92, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "45:45",
    position: "", movement: "Passez sur le côté gauche.", coaching: "Planche latérale sur le genou gauche.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 93,
    phase: "workout",
    isTransition: false,
    name: "Planche Latérale Crunch (G)",
    duration: 45,
    startTime: "46:00",
    position: "Planche latérale appui genou gauche/main gauche. Haltère main droite.",
    movement: "Crunch coude droit vers genou droit.",
    coaching: "Dernier effort sur ce bloc ! Allongez bien la jambe et le bras.",
    imageUrl: "IMG_SIDE_PLANK_CRUNCH",
    targetMuscles: "Obliques, moyen fessier",
  },
  {
    id: 94, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "46:45",
    position: "", movement: "Asseyez-vous.", coaching: "On passe au tabletop inversé.", imageUrl: TRANS, targetMuscles: "",
  },

  // --- BLOC 7 : FINISHER ---
  {
    id: 95,
    phase: "workout",
    isTransition: false,
    name: "Tabletop inversé Marche",
    duration: 45,
    startTime: "47:00",
    position: "Assis, mains derrière le dos, montez le bassin pour former une table.",
    movement: "Maintenez le bassin haut et levez un genou vers la poitrine, reposez, puis l'autre.",
    coaching: "Ouvrez la poitrine. Poussez fort dans les talons. Si c'est trop dur, maintenez simplement la position.",
    imageUrl: "IMG_TABLETOP",
    targetMuscles: "Triceps, fessiers, épaules",
  },
  {
    id: 96, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "47:45",
    position: "", movement: "Restez assis.", coaching: "On enchaîne avec les dips.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 97,
    phase: "workout",
    isTransition: false,
    name: "Triceps Dips au sol",
    duration: 45,
    startTime: "48:00",
    position: "Assis, mains derrière le dos, doigts vers l'avant, genoux pliés.",
    movement: "Pliez les coudes pour descendre les fesses vers le sol. Poussez pour remonter.",
    coaching: "Coudes vers l'arrière, pas sur les côtés ! Serrez les triceps en haut.",
    imageUrl: "IMG_DIPS",
    targetMuscles: "Triceps",
  },
  {
    id: 98, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "48:45",
    position: "", movement: "Allongez-vous sur le dos.", coaching: "Dernier exercice du workout ! On donne tout.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 99,
    phase: "workout",
    isTransition: false,
    name: "Leg Lower avec Haltère",
    duration: 45,
    startTime: "49:00",
    position: "Allongé dos, jambes tendues vers le plafond. Haltère tenu à deux mains au-dessus de la poitrine.",
    movement: "Descendez lentement les deux jambes vers le sol (sans toucher). Remontez vers le plafond.",
    coaching: "Bas du dos PLAQUÉ ! Si ça tire dans le dos, pliez légèrement les genoux. Expirez en descendant.",
    imageUrl: "IMG_LEG_LOWER",
    targetMuscles: "Abdominaux inférieurs, psoas",
  },
  {
    id: 100, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "49:45",
    position: "", movement: "Restez sur le dos.", coaching: "On passe au dernier bloc : Toe Taps.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 101,
    phase: "workout",
    isTransition: false,
    name: "Toe Taps Pilates",
    duration: 45,
    startTime: "50:00",
    position: "Allongé dos, jambes en tabletop (genoux à 90°).",
    movement: "Descendez un pied pour effleurer le sol, remontez en tabletop. Alternez.",
    coaching: "Gardez le bas du dos plaqué ! Le mouvement est petit mais intense. Expirez en descendant le pied.",
    imageUrl: "IMG_TOE_TAPS",
    targetMuscles: "Transverse, abdominaux",
  },
  {
    id: 102, phase: "workout", isTransition: true, name: "Transition", duration: 15, startTime: "50:45",
    position: "", movement: "Posez tout le matériel.", coaching: "BRAVO ! Posez les poids, on passe au retour au calme.", imageUrl: TRANS, targetMuscles: "",
  },

  // ============================================================
  // PHASE 3 — RETOUR AU CALME & ETIREMENTS (~8 min)
  // ============================================================
  {
    id: 103,
    phase: "cooldown",
    isTransition: false,
    name: "Posture de l'Enfant",
    duration: 45,
    startTime: "51:00",
    position: "Genoux écartés, fesses sur les talons, bras tendus devant.",
    movement: "Respirez profondément. Laissez le front toucher le tapis. Étirez les bras le plus loin possible.",
    coaching: "Fermez les yeux. Inspirez par le nez sur 4 temps, expirez par la bouche sur 6 temps. Relâchez tout.",
    imageUrl: "IMG_CHILD_POSE",
    targetMuscles: "Dos, hanches, épaules",
  },
  {
    id: 104, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "51:45",
    position: "", movement: "Restez à genoux.", coaching: "On enchaîne les vagues.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 105,
    phase: "cooldown",
    isTransition: false,
    name: "Vagues de la Colonne",
    duration: 45,
    startTime: "52:00",
    position: "Posture de l'enfant.",
    movement: "Déroulez la colonne vers l'avant pour venir en Cobra (bassin vers le sol, poitrine ouverte). Repoussez pour revenir en posture de l'enfant.",
    coaching: "Déroulez le dos vertèbre par vertèbre. Mouvement fluide et lent.",
    imageUrl: "IMG_SPINE_WAVE",
    targetMuscles: "Colonne vertébrale",
  },
  {
    id: 106, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "52:45",
    position: "", movement: "Restez à 4 pattes.", coaching: "On étire le haut du corps.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 107,
    phase: "cooldown",
    isTransition: false,
    name: "Étirement du Chiot",
    duration: 45,
    startTime: "53:00",
    position: "À 4 pattes.",
    movement: "Gardez les hanches au-dessus des genoux, avancez les mains loin devant et laissez fondre la poitrine vers le tapis.",
    coaching: "Sentez l'ouverture dans les épaules et le haut du dos. Laissez la gravité faire le travail.",
    imageUrl: "IMG_PUPPY_STRETCH",
    targetMuscles: "Épaules, haut du dos",
  },
  {
    id: 108, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "53:45",
    position: "", movement: "Allongez-vous sur le dos.", coaching: "On étire les fessiers.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 109,
    phase: "cooldown",
    isTransition: false,
    name: "Étirement Fessier (D)",
    duration: 45,
    startTime: "54:00",
    position: "Allongé sur le dos.",
    movement: "Croisez la cheville droite sur le genou gauche (en forme de 4). Attrapez l'arrière de la cuisse gauche et tirez vers vous.",
    coaching: "On étire le fessier droit qui a bien travaillé. Gardez les épaules détendues sur le tapis.",
    imageUrl: "IMG_GLUTE_STRETCH",
    targetMuscles: "Fessiers, piriforme",
  },
  {
    id: 110, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "54:45",
    position: "", movement: "Changez de jambe.", coaching: "On inverse les jambes.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 111,
    phase: "cooldown",
    isTransition: false,
    name: "Étirement Fessier (G)",
    duration: 45,
    startTime: "55:00",
    position: "Allongé sur le dos.",
    movement: "Croisez la cheville gauche sur le genou droit. Tirez vers vous.",
    coaching: "Respirez profondément. Relâchez toutes les tensions.",
    imageUrl: "IMG_GLUTE_STRETCH",
    targetMuscles: "Fessiers, piriforme",
  },
  {
    id: 112, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "55:45",
    position: "", movement: "Ramenez les genoux à la poitrine.", coaching: "On étire le bas du dos.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 113,
    phase: "cooldown",
    isTransition: false,
    name: "Genoux à la Poitrine",
    duration: 45,
    startTime: "56:00",
    position: "Allongé sur le dos, genoux ramenés vers la poitrine.",
    movement: "Entourez vos genoux avec les bras. Balancez doucement de droite à gauche pour masser le bas du dos.",
    coaching: "Massage doux du bas du dos. Relâchez la nuque. Respirez profondément.",
    imageUrl: "IMG_KNEES_CHEST",
    targetMuscles: "Lombaires, bas du dos",
  },
  {
    id: 114, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "56:45",
    position: "", movement: "Tendez les jambes.", coaching: "On passe à la torsion.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 115,
    phase: "cooldown",
    isTransition: false,
    name: "Torsion allongée (D)",
    duration: 45,
    startTime: "57:00",
    position: "Allongé sur le dos, bras en croix.",
    movement: "Ramenez le genou droit vers la poitrine, puis laissez-le tomber vers la gauche. Regardez vers la droite.",
    coaching: "Gardez les deux épaules au sol. Sentez l'étirement dans le bas du dos et la hanche.",
    imageUrl: "IMG_TWIST",
    targetMuscles: "Lombaires, obliques, hanches",
  },
  {
    id: 116, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "57:45",
    position: "", movement: "Changez de côté.", coaching: "Même chose de l'autre côté.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 117,
    phase: "cooldown",
    isTransition: false,
    name: "Torsion allongée (G)",
    duration: 45,
    startTime: "58:00",
    position: "Allongé sur le dos, bras en croix.",
    movement: "Ramenez le genou gauche vers la poitrine, puis laissez-le tomber vers la droite. Regardez vers la gauche.",
    coaching: "Derniers instants de la séance. Profitez de cet étirement. Relâchez tout le corps.",
    imageUrl: "IMG_TWIST",
    targetMuscles: "Lombaires, obliques, hanches",
  },
  {
    id: 118, phase: "cooldown", isTransition: true, name: "Transition", duration: 15, startTime: "58:45",
    position: "", movement: "Allongez-vous complètement.", coaching: "Position finale.", imageUrl: TRANS, targetMuscles: "",
  },
  {
    id: 119,
    phase: "cooldown",
    isTransition: false,
    name: "Savasana (Relaxation)",
    duration: 60,
    startTime: "59:00",
    position: "Allongé sur le dos, bras le long du corps, paumes vers le ciel, jambes relâchées.",
    movement: "Ne bougez plus. Fermez les yeux. Laissez votre corps s'enfoncer dans le tapis.",
    coaching: "Bravo à tous pour cette séance Pilates Strength d'une heure ! Vous avez travaillé tout le corps. Prenez un moment pour vous féliciter. Pensez à bien vous hydrater. À très bientôt avec Coach Mimi !",
    imageUrl: "IMG_SAVASANA",
    targetMuscles: "Relaxation totale",
  },
];

// Apply real image URLs to all exercises
exercises.forEach((ex) => {
  if (ex.imageUrl && !ex.imageUrl.startsWith("http")) {
    ex.imageUrl = resolveImageUrl(ex.imageUrl);
  }
});

export const TOTAL_DURATION = exercises.reduce((sum, ex) => sum + ex.duration, 0);

export function getExerciseNumber(exercise: Exercise): number {
  const mainExercises = exercises.filter((e) => !e.isTransition);
  const idx = mainExercises.findIndex((e) => e.id === exercise.id);
  return idx + 1;
}

export function getTotalMainExercises(): number {
  return exercises.filter((e) => !e.isTransition).length;
}
